ecg:
  # input data
  input_channels: 1
  input_variates: 12
  time_steps: 1008
  input_size: [1, 12, 1008]

  # model
  model_name: vit_baseDeep_patchX
  patch_height: 1
  patch_width: 24
  patch_size: [1, 24]
  drop_path_rate: 0.2
  use_adapter: false
  adapter_bottleneck_dim: 64
  nb_classes: 1
  ignore_pos_embed_y: false
  freeze_pos_embed_y: false
  masking_blockwise: 0
  mask_ratio: 0
  mask_c_ratio: 0
  mask_t_ratio: 0

  # use gradient checkpoint
  use_checkpoint: true

# token aggregation
token_aggregation:
  ecg:
    strategy: mean # mean / max / attention / cls
    num_heads: 4 # only relevant for attention

alignment:
  proj_embed_dim: 512
  width_factor: 8
  alignment_type: linear # options: sail / simclr / legacy / linear
  sail:
    sharelock: false
    linear_type: star